name: Playwright Tests

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read
      pages: write
      id-token: write

    env:
      BASE_URL: ${{ github.event.inputs.environment || 'staging' }}
      USERNAME_REPAIRER1: ${{ secrets.USERNAME_REPAIRER1 }}
      PASSWORD_REPAIRER1: ${{ secrets.PASSWORD_REPAIRER1 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure CLI and reporter
        run: npm i -D allure-playwright allure-commandline

        #Run Tests (capture exit code)
      - name: Run Playwright tests
        id: run_tests
        run: |
          set +e
          npx playwright test
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          exit 0

        #If Playwright crashed before executing tests
      - name: Fail if execution crashed
        if: steps.run_tests.outputs.exit_code != '0' && github.event_name != 'push'
        run: exit 1
        
        #Preserve History
      - name: Checkout gh-pages branch
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch origin gh-pages || true
          git checkout gh-pages || true

      - name: Copy previous Allure history
        if: github.ref == 'refs/heads/main'
        run: |
          if [ -d "history" ]; then
            mkdir -p allure-results/history
            cp -r history/* allure-results/history || true
          fi

        #Generate Report
      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Preserve history in new report
        if: github.ref == 'refs/heads/main'
        run: |
          if [ -d "allure-results/history" ]; then
            mkdir -p allure-report/history
            cp -r allure-results/history/* allure-report/history || true
          fi

      # Deploy ONLY on push to main
      - name: Upload Allure report for GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v4
        with:
          path: allure-report

      - name: Deploy Allure report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
